version: '3.8'

services:
  # openchargemapimporter:
  #   build: 
  #     dockerfile: Dockerfile
  #     context: .
  #   ports:
  #     - "4000:4000"
  #   environment:
  #     - NODE_ENV=development
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules
  #   command: ["npm", "start"]

  mongo:
    image: mongo:4.2
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
